var ni = document.getElementById("name-input")
var mi = document.getElementById("mark-input")
var dt = document.getElementById("data-table")
var rt = document.getElementById("report-table")
var studentcount = 0
var passedstudents =0
var failedstudents =0
var nestudents=0
var sww = 0
var highm = 0
var lowm = 100
var avgm =0
